import type {Metadata} from "next";
import Link from "next/link";
import {Phone,MapPin,ArrowUpRight} from "lucide-react";
import {getProduct} from "@/lib/products";
import {formatStorage,conditionLabels} from "@/lib/catalogue";
import {ContactEnquiry} from "@/components/contact-enquiry";
import store from "@/data/store.json";
export const metadata:Metadata={title:"Talk to MizikTech",description:"Call MizikTech in Lagos to confirm device prices, stock and condition, or get help choosing your next upgrade.",alternates:{canonical:"/contact"}};
export default async function ContactPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){const q=await searchParams;const p=q.product?getProduct(q.product):undefined;const storage=Number(q.storage),ram=Number(q.ram);const chosen=p?[p.name,p.storageGb.includes(storage)?formatStorage(storage):"",p.ramGb.includes(ram)?ram+"GB memory":"",p.colors.includes(q.color||"")?q.color:"",q.condition&&q.condition in conditionLabels?conditionLabels[q.condition as keyof typeof conditionLabels]+" condition preferred":""].filter(Boolean).join(" · "):"a device";const message=`Hi MizikTech, I’m interested in ${chosen}. Please confirm the price, available configurations, condition and stock. My budget is: `;return <main id="main-content" className="contact-page container"><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><span>Contact</span></nav><div className="contact-page-grid"><div className="contact-page-copy"><span className="eyebrow">REAL PEOPLE. GOOD ADVICE.</span><h1>Let’s find<br/>your fit.</h1><p>Tell us what you need from your next device. We’ll help you explore your options and confirm the details.</p><div className="contact-information"><a href={"tel:"+store.phone}><Phone size={22}/><span><small>Call MizikTech</small><strong>{store.phoneDisplay}</strong></span><ArrowUpRight size={20}/></a><div><MapPin size={22}/><span><small>Our roots</small><strong>{store.address||store.location}</strong></span></div></div><p className="contact-guidance">Before purchasing, ask about the device’s condition, included accessories, warranty and delivery arrangements.</p><Link href="/catalogue" className="text-link">Keep exploring devices <ArrowUpRight size={18}/></Link></div><ContactEnquiry initialMessage={message}/></div></main>;}
