"use client";
import Link from "next/link";
import {useState} from "react";
import {MessageCircle,ArrowUpRight,Info} from "lucide-react";
import {Product,formatStorage,formatPrice,conditionLabels} from "@/lib/catalogue";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "@/components/ui/select";
export function ProductOptions({product:p}:{product:Product}){
 const first=p.offers.find(o=>o.availability==="in-stock")||p.offers[0];
 const [storage,setStorage]=useState(first?.storageGb||p.storageGb[0]),[memory,setMemory]=useState(first?.ramGb||p.memoryByStorage?.[String(first?.storageGb||p.storageGb[0])]?.[0]||p.ramGb[0]),[color,setColor]=useState(first?.color||p.colors[0]||"Any colour"),[condition,setCondition]=useState<string>(first?.condition||"any");
 const memories=p.memoryByStorage?.[String(storage)]||p.ramGb;
 const matches=p.offers.filter(o=>o.storageGb===storage&&(!memory||o.ramGb===memory)&&o.color===color&&(condition==="any"||o.condition===condition));
 const offer=matches.find(o=>o.availability==="in-stock")||matches[0];
 const query=new URLSearchParams({product:p.slug,storage:String(storage),color,condition});if(memory)query.set("ram",String(memory));
 function changeStorage(s:number){setStorage(s);const allowed=p.memoryByStorage?.[String(s)]||p.ramGb;if(memory&&!allowed.includes(memory))setMemory(allowed[0]);}
 return <div className="product-options"><div className="detail-price"><strong>{offer?.price!=null?formatPrice(offer.price):"Price on request"}</strong><span className={offer?.availability==="in-stock"?"verified-availability":""}>{offer?offer.availability==="in-stock"?"In stock":offer.availability==="preorder"?"Pre-order":"Currently out of stock":"Enquire for availability"}</span></div><div className="config-intro"><h2>Choose your preference</h2><p>We’ll confirm the available configuration and final price.</p></div><fieldset className="configuration-choice"><legend>Storage</legend><div className="option-buttons">{p.storageGb.map(s=><button type="button" aria-pressed={storage===s} className={storage===s?"selected":""} onClick={()=>changeStorage(s)} key={s}>{formatStorage(s)}</button>)}</div></fieldset>{memories.length>0&&<fieldset className="configuration-choice"><legend>{p.category==="laptops"?"Unified memory":"RAM"}</legend><div className="option-buttons">{memories.map(m=><button type="button" aria-pressed={memory===m} className={memory===m?"selected":""} key={m} onClick={()=>setMemory(m)}>{m}GB</button>)}</div></fieldset>}<div className="configuration-selects">{p.colors.length>0&&<div><label id="colour-label">Colour</label><Select value={color} onValueChange={setColor}><SelectTrigger aria-labelledby="colour-label" className="catalogue-select"><SelectValue/></SelectTrigger><SelectContent>{p.colors.map(c=><SelectItem value={c} key={c}>{c}</SelectItem>)}</SelectContent></Select></div>}<div><label id="condition-label">Condition</label><Select value={condition} onValueChange={setCondition}><SelectTrigger aria-labelledby="condition-label" className="catalogue-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="any">Ask about condition</SelectItem>{Object.entries(conditionLabels).map(([value,label])=><SelectItem value={value} key={value}>{label}</SelectItem>)}</SelectContent></Select></div></div><div className="selection-summary" aria-live="polite"><span>{formatStorage(storage)}{memory?" / "+memory+"GB memory":""} · {color}</span><strong>Condition: {offer?conditionLabels[offer.condition]:condition==="any"?"To be confirmed":conditionLabels[condition as keyof typeof conditionLabels]+" requested"}</strong></div>{p.configurationNote&&<p className="configuration-note"><Info size={16}/><span>{p.configurationNote}</span></p>}{offer?.purchaseUrl&&offer.availability==="in-stock"?<a href={offer.purchaseUrl} className="button purchase-button" rel="noopener noreferrer">Purchase this configuration <ArrowUpRight size={20}/></a>:<Link href={"/contact?"+query.toString()} className="button purchase-button">Enquire about this device <MessageCircle size={20}/></Link>}<p className="purchase-note">Confirm price, condition, warranty and delivery with MizikTech before making payment.</p></div>;
}
