"use client";
import Image from "next/image";
import {useState} from "react";
import {Maximize2,ChevronLeft,ChevronRight} from "lucide-react";
import type {ProductImage} from "@/lib/catalogue";
import {Dialog,DialogTrigger,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
export function ProductGallery({images,name}:{images:ProductImage[];name:string}){
 const [index,setIndex]=useState(0);const image=images[index];
 const move=(direction:number)=>setIndex(i=>(i+direction+images.length)%images.length);
 return <div className="product-gallery"><Dialog><div className="gallery-main"><Image src={image.src} alt={image.alt} width={image.width} height={image.height} priority unoptimized/><DialogTrigger asChild><button className="gallery-expand" aria-label={"Enlarge image of "+name}><Maximize2 size={19}/></button></DialogTrigger>{images.length>1&&<div className="gallery-arrows"><button onClick={()=>move(-1)} aria-label="Previous image"><ChevronLeft/></button><span>{index+1} / {images.length}</span><button onClick={()=>move(1)} aria-label="Next image"><ChevronRight/></button></div>}</div><DialogContent className="gallery-dialog"><DialogHeader><DialogTitle>{name}</DialogTitle><DialogDescription>{image.view}{image.color?" · "+image.color:""}</DialogDescription></DialogHeader><Image src={image.src} alt={image.alt} width={image.width} height={image.height} unoptimized/>{images.length>1&&<div className="zoom-controls"><button className="icon-button" onClick={()=>move(-1)} aria-label="Previous image"><ChevronLeft/></button><span>{index+1} of {images.length}</span><button className="icon-button" onClick={()=>move(1)} aria-label="Next image"><ChevronRight/></button></div>}</DialogContent></Dialog>{images.length>1&&<div className="gallery-thumbnails" aria-label="Product images">{images.map((im,i)=><button key={im.src} aria-label={"Show image "+(i+1)+": "+im.view} aria-pressed={index===i} className={index===i?"selected":""} onClick={()=>setIndex(i)}><Image src={im.thumbnail||im.src} alt="" width={im.width} height={im.height} unoptimized/></button>)}</div>}<p className="gallery-note">{image.credit&&<span className="gallery-credit">{image.credit}. </span>}Official product imagery. The condition of your individual device will be confirmed before purchase.</p></div>;
}
