"use client";
import Link from "next/link";
import Image from "next/image";
import {Search,Menu,ArrowUpRight} from "lucide-react";
import {useState} from "react";
import {Sheet,SheetTrigger,SheetContent,SheetHeader,SheetTitle,SheetDescription,SheetClose} from "@/components/ui/sheet";
import store from "@/data/store.json";
export function SiteHeader(){
 const [open,setOpen]=useState(false);
 return <><a href="#main-content" className="skip-link">Skip to content</a><div className="announcement"><div className="container"><span>Quality devices, reliable support after every sale.</span><Link href="/contact">Let’s talk <ArrowUpRight size={14}/></Link></div></div><header className="site-header"><div className="container header-row"><Link href="/" className="site-logo" aria-label="MizikTech home"><Image src="/brand/logo-crisp.png" width={1617} height={264} alt="MizikTech" priority unoptimized/></Link><nav className="desktop-nav" aria-label="Main navigation"><Link href="/catalogue/phones">Phones</Link><Link href="/catalogue/tablets">Tablets</Link><Link href="/catalogue/laptops">Laptops</Link><Link href="/catalogue/watches">Watches</Link><Link href="/catalogue">All devices</Link></nav><form className="header-search" action="/catalogue" role="search"><Search size={18}/><label className="sr-only" htmlFor="site-search">Search devices</label><input type="search" name="q" id="site-search" placeholder="Find your next device"/><button aria-label="Search catalogue"><ArrowUpRight size={18}/></button></form><a href={"https://wa.me/"+store.whatsapp.replace(/\D/g,"")} className="header-contact" aria-label="Chat with MizikTech on WhatsApp" target="_blank" rel="noopener noreferrer"><Image src="/brand/whatsapp.svg" width={22} height={22} alt=""/></a><Sheet open={open} onOpenChange={setOpen}><SheetTrigger asChild><button className="mobile-menu icon-button" aria-label="Open menu"><Menu size={24}/></button></SheetTrigger><SheetContent className="navigation-sheet" overlayClassName="navigation-overlay"><SheetHeader><SheetTitle>Explore MizikTech</SheetTitle><SheetDescription>Your next upgrade starts here.</SheetDescription></SheetHeader><nav aria-label="Mobile navigation">{[["All devices","/catalogue"],["Phones","/catalogue/phones"],["Tablets","/catalogue/tablets"],["Laptops","/catalogue/laptops"],["Watches","/catalogue/watches"],["Talk to MizikTech","/contact"]].map(([label,url])=><SheetClose asChild key={url}><Link href={url}>{label}<ArrowUpRight size={21}/></Link></SheetClose>)}</nav></SheetContent></Sheet></div></header></>;
}
