"use client";
import Link from "next/link";
import Image from "next/image";
import {Search,Menu,ArrowUpRight,MessageCircle} from "lucide-react";
import {useState} from "react";
import {Sheet,SheetTrigger,SheetContent,SheetHeader,SheetTitle,SheetDescription,SheetClose} from "@/components/ui/sheet";
export function SiteHeader(){
 const [open,setOpen]=useState(false);
 return <><a href="#main-content" className="skip-link">Skip to content</a><div className="announcement"><div className="container"><span>Quality devices. Honest prices. Quality without the guesswork.</span><Link href="/contact">Let’s talk <ArrowUpRight size={14}/></Link></div></div><header className="site-header"><div className="container header-row"><Link href="/" className="site-logo" aria-label="MizikTech home"><Image src="/brand/logo.svg" width={196} height={32} alt="MizikTech" priority unoptimized/></Link><nav className="desktop-nav" aria-label="Main navigation"><Link href="/catalogue/phones">Phones</Link><Link href="/catalogue/tablets">Tablets</Link><Link href="/catalogue/laptops">Laptops</Link><Link href="/catalogue">All devices</Link></nav><form className="header-search" action="/catalogue" role="search"><Search size={18}/><label className="sr-only" htmlFor="site-search">Search devices</label><input type="search" name="q" id="site-search" placeholder="Find your next device"/><button aria-label="Search catalogue"><ArrowUpRight size={18}/></button></form><Link href="/contact" className="header-contact" aria-label="Contact MizikTech"><MessageCircle size={22}/></Link><Sheet open={open} onOpenChange={setOpen}><SheetTrigger asChild><button className="mobile-menu icon-button" aria-label="Open menu"><Menu size={24}/></button></SheetTrigger><SheetContent className="navigation-sheet"><SheetHeader><SheetTitle>Explore MizikTech</SheetTitle><SheetDescription>Your next upgrade starts here.</SheetDescription></SheetHeader><nav aria-label="Mobile navigation">{[["All devices","/catalogue"],["Phones","/catalogue/phones"],["Tablets","/catalogue/tablets"],["Laptops","/catalogue/laptops"],["Talk to MizikTech","/contact"]].map(([label,url])=><SheetClose asChild key={url}><Link href={url}>{label}<ArrowUpRight size={21}/></Link></SheetClose>)}</nav></SheetContent></Sheet></div></header></>;
}
